<?php
	$domain='localhost';
	$domain_punicode=$domain;
	$dbhost='localhost';
	$dbuser='root';
	$dbpwd='rootpwd1';
	$dbname='microtrackdb';
	$dbtableprefix='wikione_';
	$use_authorization=true;
	$openid='openid.yandex.ru/kapojko';
?>